[package]
name = "p16"
version = "0.1.0"
authors = ["Maximiliano Sandoval R. <msandova@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
num-bigint = "0.2.3"
num-traits = "0.2.8"
