// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

var sum int = 0

func main() {
	a := 0
	b := 1
	for n := 1; n < 4e6; {

		n = a + b
		a = b
		b = n

		if n%2 == 0 {
			sum += n
		}
	}
	fmt.Println(sum)
}
